// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddAccountFromURI(arg1:string):Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<main.AccountWithCode>>;

export function ParseOTPAuthURI(arg1:string):Promise<string>;
