CREATE DATABASE IF NOT EXISTS db;

CREATE TABLE IF NOT EXISTS db.orders_v2 (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
) ENGINE = InnoDB;

INSERT INTO
  db.orders_v2 (name)
VALUES
  ('order1');
