// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package main

type Blog struct {
	ID   int64
	Name string
	Url  string
}

type Post struct {
	ID      int64
	Title   string
	Content string
	UserID  int64
	BlogID  int64
}

type User struct {
	ID    int64
	Name  string
	Email string
}
