services:
  postgres:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
